const BROWSER_TYPE = "chrome";
const MIN_VIDEO_SIZE = 100000;
const API_URL = "https://api.selectext.app";
const WEBSITE_URL = "https://selectext.app";
const CANVAS_CAPTURE_SITE_LIST = ["youtube.com", "vimeo.com", "kaltura.com", "coursera.org"];
const PAUSED_BY_DEFAULT_SITE_LIST = [];
const MAX_VIDEO_FRAME_WIDTH = 2048;
const WEB_STORE_URL = "https://chromewebstore.google.com/detail/selectext-copy-text-from/gkkdmjjodidppndkbkhhknakbeflbomf";
const EXTENSION_SHORTCUTS_URL = "chrome://extensions/shortcuts";